---
abstract: 'Profile time query took with DBIC::Schema in your Catalyst application.'
author:
  - 'Ryuzo Yamamoto, <ryuzo.yamamoto@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-DBIC-Schema-Profiler
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.80016
  Catalyst::Model::DBIC::Schema: 0.35
  DBIx::Class: 0.08115
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
