# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-DBIC-Schema-Profiler
version:      0.04
version_from: lib/Catalyst/Plugin/DBIC/Schema/Profiler.pm
installdirs:  site
requires:
    Catalyst:                      5.7003
    Catalyst::Model::DBIC::Schema: 0.18
    DBIx::Class:                   0.07002

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
