--- #YAML:1.0
name:                Catalyst-Plugin-DBIC-Schema-Profiler
version:             0.01
abstract:            DBIC::Schema profiler plugin for Catalyst
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Catalyst:                      5.7003
    DBIx::Class:                   0.07002
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Yamamoto Ryuzo <ryuzo.yamamoto@gmail.com>
